title = "Ahmad Kamiludin"
baseURL = "https://kamiludin.github.io/Kamil_Portfolio/"
languageCode = "en-us"
theme = "ananke"
#themesDir = "../.."
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
canonifyURLs = true
[languages]
  [languages.en]
    title = "Ahmad Kamiludin"
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = "https://www.facebook.com/ahmad.kamiludin.14/"
  twitter = ""
  instagram = "https://www.instagram.com/kamiludin18/"
  youtube = ""
  github = "https://github.com/kamiludin"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/ahmad-kamiludin-9739b61b6/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  tiktok = ""

  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/Data_Analyst.jpg"
  recent_posts_number = 2
